/*
 * ARX: Powerful Data Anonymization
 * Copyright 2012 - 2015 Florian Kohlmayer, Fabian Prasser
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.deidentifier.arx.test;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collection;

import org.deidentifier.arx.ARXConfiguration;
import org.deidentifier.arx.AttributeType.Hierarchy;
import org.deidentifier.arx.criteria.DPresence;
import org.deidentifier.arx.criteria.HierarchicalDistanceTCloseness;
import org.deidentifier.arx.criteria.KAnonymity;
import org.deidentifier.arx.criteria.RecursiveCLDiversity;
import org.deidentifier.arx.metric.Metric;
import org.deidentifier.arx.test.ConfigurationUtil.Dataset;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

/**
 * Test for data transformations.
 *
 * @author Fabian Prasser
 * @author Florian Kohlmayer
 */
@RunWith(Parameterized.class)
public class TestAnonymizationCombinations extends AbstractAnonymizationTest {
    
    /**
     * 
     *
     * @return
     * @throws IOException
     */
    @Parameters(name = "{index}:[{0}]")
    public static Collection<Object[]> cases() throws IOException {
        return Arrays.asList(new Object[][] {
                                              /* 0 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 37223.2491248282, new int[] { 1, 4, 1, 1, 1, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 35461.300017243804, new int[] { 0, 2, 1, 2, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 42481.619746031596, new int[] { 1, 4, 1, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))), "occupation", Dataset.ADULT, 398400.0741806447, new int[] { 0, 4, 1, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)), "occupation", Dataset.ADULT, 324620.5269918692, new int[] { 1, 1, 1, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 42481.619746031596, new int[] { 1, 4, 1, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))), "occupation", Dataset.ADULT, 398400.0741806447, new int[] { 0, 4, 1, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 39177.7411830619, new int[] { 1, 4, 1, 1, 2, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)), "occupation", Dataset.ADULT, 324620.5269918692, new int[] { 1, 1, 1, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 195829.0291224279, new int[] { 5, 4, 1, 0, 1, 4, 4 }, false) },
                                              /* 10 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 195829.0291224279, new int[] { 5, 4, 1, 0, 1, 3, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 195829.0291224279, new int[] { 5, 4, 1, 0, 1, 3, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", Dataset.CUP, 2023751.243421626, new int[] { 4, 4, 1, 2, 1, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)), "RAMNTALL", Dataset.CUP, 1961244.4822559545, new int[] { 4, 4, 1, 1, 1, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 195829.0291224279, new int[] { 5, 4, 1, 0, 1, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", Dataset.CUP, 2023751.243421626, new int[] { 4, 4, 1, 2, 1, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 195829.0291224279, new int[] { 5, 4, 1, 0, 1, 3, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)), "RAMNTALL", Dataset.CUP, 1961244.4822559545, new int[] { 4, 4, 1, 1, 1, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 142414.2491462392, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 121297.9782432485, new int[] { 5, 2, 2, 0, 1, 2, 0 }, false) },
                                              /* 20 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 151844.6761858994, new int[] { 2, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))), "istatenum", Dataset.FARS, 1429434.050891089, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)), "istatenum", Dataset.FARS, 1201007.0880104562, new int[] { 0, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 151844.6761858994, new int[] { 2, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))), "istatenum", Dataset.FARS, 1429434.050891089, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 142414.2491462392, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)), "istatenum", Dataset.FARS, 1201007.0880104562, new int[] { 0, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 400542.9546949434, new int[] { 1, 0, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 400542.9546949434, new int[] { 1, 0, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 574838.3678280927, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                                              /* 30 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", Dataset.ATUS, 5760138.103541854, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)), "Highest level of school completed", Dataset.ATUS, 3478926.4429797237, new int[] { 0, 0, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 574838.3678280927, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", Dataset.ATUS, 5760138.103541854, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 490137.6908435117, new int[] { 0, 4, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)), "Highest level of school completed", Dataset.ATUS, 4912828.240033204, new int[] { 0, 4, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1287579.5821546589, new int[] { 0, 0, 0, 3, 4, 1, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1287579.5821546589, new int[] { 0, 0, 0, 3, 4, 1, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1589251.3824409053, new int[] { 0, 0, 1, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", Dataset.IHIS, 1.4719292081181683E7, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              /* 40 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)), "EDUC", Dataset.IHIS, 9503511.261799559, new int[] { 0, 0, 2, 3, 0, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1589251.3824409053, new int[] { 0, 0, 1, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", Dataset.IHIS, 1.4719292081181683E7, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1405067.4080803706, new int[] { 0, 0, 1, 3, 4, 1, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)), "EDUC", Dataset.IHIS, 1.2258628558792587E7, new int[] { 0, 0, 0, 3, 3, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)), "occupation", Dataset.ADULT, 180132.40848244698, new int[] { 0, 0, 1, 1, 2, 2, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)), "RAMNTALL", Dataset.CUP, 1252060.0068011207, new int[] { 2, 4, 1, 0, 0, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)), "istatenum", Dataset.FARS, 560028.8197749631, new int[] { 0, 0, 2, 3, 0, 0, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)), "Highest level of school completed", Dataset.ATUS, 1337026.078203367, new int[] { 0, 1, 0, 0, 0, 0, 1, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)), "EDUC", Dataset.IHIS, 5823479.072286698, new int[] { 0, 0, 0, 2, 0, 1, 0, 1 }, false) },
                                              /* 50 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 25247.843728345997, new int[] { 1, 0, 1, 2, 2, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 40089.9423426752, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))), "occupation", Dataset.ADULT, 367061.3691338439, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 28551.7222913157, new int[] { 1, 0, 1, 2, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)), "occupation", Dataset.ADULT, 198181.4042332967, new int[] { 1, 0, 1, 1, 2, 2, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 140991.2852327497, new int[] { 3, 4, 0, 2, 0, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 166085.6968687116, new int[] { 4, 4, 1, 2, 0, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", Dataset.CUP, 1377036.0221522974, new int[] { 2, 4, 1, 2, 0, 3, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 140991.2852327497, new int[] { 3, 4, 0, 2, 0, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)), "RAMNTALL", Dataset.CUP, 1202354.6618344877, new int[] { 2, 4, 1, 0, 0, 3, 1 }, false) },
                                              /* 60 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 88717.72875464789, new int[] { 2, 0, 3, 3, 0, 0, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 121171.9073113775, new int[] { 5, 2, 1, 1, 0, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))), "istatenum", Dataset.FARS, 913268.7198249138, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 91430.99721202659, new int[] { 2, 0, 3, 3, 0, 1, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)), "istatenum", Dataset.FARS, 585933.0095846694, new int[] { 0, 2, 0, 1, 1, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 212656.0007008077, new int[] { 0, 2, 0, 1, 1, 1, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 510614.55166065297, new int[] { 0, 5, 0, 0, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", Dataset.ATUS, 4970273.35942406, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 348418.9288637205, new int[] { 0, 4, 0, 1, 2, 0, 1, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)), "Highest level of school completed", Dataset.ATUS, 3224480.405684781, new int[] { 0, 4, 0, 1, 2, 0, 0, 2 }, false) },
                                              /* 70 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 958639.1926385858, new int[] { 0, 1, 2, 2, 0, 1, 1, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1471763.5565151938, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", Dataset.IHIS, 1.4719292081181683E7, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1113232.2757912248, new int[] { 0, 0, 1, 2, 3, 1, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)), "EDUC", Dataset.IHIS, 7735322.29514608, new int[] { 0, 0, 0, 1, 3, 0, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 25949.0068665567, new int[] { 1, 0, 1, 2, 2, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 40282.23779327559, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))), "occupation", Dataset.ADULT, 375361.41655411746, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 28759.669970588497, new int[] { 1, 0, 1, 2, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)), "occupation", Dataset.ADULT, 209764.96161974416, new int[] { 1, 0, 1, 1, 2, 2, 2, 0 }, false) },
                                              /* 80 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 143476.1692988247, new int[] { 3, 4, 1, 1, 0, 3, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 167669.48564213628, new int[] { 4, 4, 1, 2, 0, 3, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", Dataset.CUP, 1407619.3716609064, new int[] { 3, 4, 1, 0, 0, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 143476.1692988247, new int[] { 3, 4, 1, 1, 0, 3, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)), "RAMNTALL", Dataset.CUP, 1254396.0338242182, new int[] { 2, 4, 1, 0, 0, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 93329.75289569901, new int[] { 2, 0, 3, 3, 0, 0, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 122965.0956511249, new int[] { 5, 2, 1, 1, 0, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))), "istatenum", Dataset.FARS, 958932.8909394152, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 96001.27991005548, new int[] { 2, 0, 3, 3, 0, 1, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)), "istatenum", Dataset.FARS, 630178.7565353523, new int[] { 0, 2, 1, 1, 0, 2, 0 }, false) },
                                              /* 90 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 245635.22647061598, new int[] { 0, 2, 0, 1, 1, 1, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 524320.641588512, new int[] { 0, 5, 0, 0, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", Dataset.ATUS, 5108199.8005006835, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 379027.95627973945, new int[] { 0, 4, 0, 1, 2, 0, 1, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)), "Highest level of school completed", Dataset.ATUS, 3536911.5162082445, new int[] { 0, 4, 0, 0, 2, 0, 1, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1028591.356117628, new int[] { 0, 1, 2, 2, 0, 1, 1, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1481940.863625334, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", Dataset.IHIS, 1.4719292081181683E7, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1185607.5242246124, new int[] { 0, 0, 1, 2, 3, 1, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)), "EDUC", Dataset.IHIS, 8460989.1661296, new int[] { 0, 0, 0, 1, 3, 0, 0, 1 }, false) },
                                              /* 100 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 33649.9118226187, new int[] { 1, 4, 1, 1, 0, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 40089.9423426752, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))), "occupation", Dataset.ADULT, 367061.3691338439, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 188685.11376583832, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 188685.11376583832, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", Dataset.CUP, 1377036.0221522974, new int[] { 2, 4, 1, 2, 0, 3, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 130155.7199192575, new int[] { 3, 2, 3, 0, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 142414.2491462392, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))), "istatenum", Dataset.FARS, 913268.7198249138, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 347941.72665935673, new int[] { 0, 0, 0, 2, 2, 2, 2, 2 }, false) },
                                              /* 110 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 528157.4793996721, new int[] { 0, 5, 0, 2, 2, 0, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", Dataset.ATUS, 4970273.35942406, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1073722.7704188202, new int[] { 0, 1, 1, 3, 0, 2, 1, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1471763.5565151938, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", Dataset.IHIS, 1.4719292081181683E7, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 33660.3063277646, new int[] { 1, 4, 1, 1, 0, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ADULT))), "occupation", Dataset.ADULT, 40282.23779327559, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("./data/adult_hierarchy_occupation.csv", ';'))), "occupation", Dataset.ADULT, 375361.41655411746, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 188698.52093140973, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.CUP))), "RAMNTALL", Dataset.CUP, 188714.6627588751, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                                              /* 120 */{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("./data/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", Dataset.CUP, 1407619.3716609064, new int[] { 3, 4, 1, 0, 0, 4, 4 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 130481.14757714301, new int[] { 3, 2, 3, 0, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.FARS))), "istatenum", Dataset.FARS, 142540.0375939336, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("./data/fars_hierarchy_istatenum.csv", ';'))), "istatenum", Dataset.FARS, 958932.8909394152, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 348509.5903491556, new int[] { 0, 0, 0, 2, 2, 2, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.ATUS))), "Highest level of school completed", Dataset.ATUS, 542366.1748035981, new int[] { 0, 5, 0, 2, 2, 0, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("./data/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", Dataset.ATUS, 5108199.8005006835, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1091154.322219155, new int[] { 0, 1, 1, 3, 0, 2, 1, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, ConfigurationUtil.getSubset(Dataset.IHIS))), "EDUC", Dataset.IHIS, 1481940.863625334, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createPrecomputedEntropyMetric(0.1d, false)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("./data/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", Dataset.IHIS, 1.4719292081181683E7, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                                              
        });
    }
    
    /**
     * 
     *
     * @param testCase
     */
    public TestAnonymizationCombinations(final ARXAnonymizationTestCase testCase) {
        super(testCase);
    }
    
}
